{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1960f19a-ed95-485c-91d1-4040829fc67c",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ==============================================================================\n",
    "# ENTERPRISE-GRADE CAPSTONE DEPLOYMENT: Zomato Bangalore AI Predictor Web App\n",
    "# FILE: E:\\Data-Science-Master-Portfolio\\06_Capstone_Final_Project\\02_Python_Machine_Learning\\app.py\n",
    "# DESCRIPTION: Streamlit production web application for interactive model inference.\n",
    "# ==============================================================================\n",
    "\n",
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import joblib\n",
    "import os\n",
    "\n",
    "# Page Configuration\n",
    "st.set_page_config(\n",
    "    page_title=\"Zomato Bangalore Market Intelligence Platform\",\n",
    "    page_icon=\"🍽️\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "# Load Serialized Model Pipeline\n",
    "@st.cache_resource\n",
    "def load_model():\n",
    "    model_path = 'model_pipeline.pkl'\n",
    "    if os.path.exists(model_path):\n",
    "        return joblib.load(model_path)\n",
    "    return None\n",
    "\n",
    "pipeline = load_model()\n",
    "\n",
    "# App Header\n",
    "st.title(\"🍽️ Zomato Bangalore Restaurant Popularity & Market Predictor\")\n",
    "st.markdown(\"### Enterprise-Grade 15-Layer Data Science Capstone Deployment\")\n",
    "st.write(\"This interactive application uses a trained Machine Learning pipeline to predict expected customer engagement (`votes`) based on operational parameters, pricing tiers, and micro-market hubs.\")\n",
    "\n",
    "if pipeline is None:\n",
    "    st.error(\"[ERROR] Model pipeline file (`model_pipeline.pkl`) not found! Please run your Jupyter notebook first to train and serialize the model.\")\n",
    "else:\n",
    "    st.sidebar.header(\"🔍 Input Restaurant Parameters\")\n",
    "    \n",
    "    # Input widgets mirroring our model features\n",
    "    col1, col2 = st.sidebar.columns(2)\n",
    "    \n",
    "    with col1:\n",
    "        online_order = st.selectbox(\"Online Order\", [\"Yes\", \"No\"])\n",
    "        book_table = st.selectbox(\"Table Booking\", [\"Yes\", \"No\"])\n",
    "        clean_rate = st.slider(\"Restaurant Rating (/5)\", min_value=1.0, max_value=5.0, value=3.8, step=0.1)\n",
    "        clean_cost = st.number_input(\"Cost for Two (INR)\", min_value=50, max_value=10000, value=600, step=50)\n",
    "        cuisine_count = st.slider(\"Cuisine Count\", min_value=1, max_value=8, value=2)\n",
    "\n",
    "    with col2:\n",
    "        has_dish_liked = st.selectbox(\"Signature Dish Flag\", [1, 0], format_func=lambda x: \"Yes (Available)\" if x == 1 else \"None Documented\")\n",
    "        location = st.selectbox(\"Micro-Market Hub\", [\n",
    "            'BTM', 'Koramangala 5th Block', 'Indiranagar', 'Whitefield', \n",
    "            'Jayanagar', 'Marathahalli', 'Bannerghatta Road', 'JP Nagar', 'HSR', 'Other'\n",
    "        ])\n",
    "        rest_type = st.selectbox(\"Restaurant Type\", [\n",
    "            'Casual Dining', 'Quick Bites', 'Cafe', 'Dessert Parlor', \n",
    "            'Delivery', 'Bar', 'Beverage Shop', 'Fine Dining', 'Other'\n",
    "        ])\n",
    "        listed_in_type = st.selectbox(\"Service Category\", [\n",
    "            'Dine-out', 'Delivery', 'Buffet', 'Cafes', 'Drinks & nightlife', 'Desserts', 'Pubs and bars'\n",
    "        ])\n",
    "\n",
    "    # Derived Feature calculation\n",
    "    cost_per_cuisine = clean_cost / (cuisine_count + 1)\n",
    "\n",
    "    # Prediction Trigger\n",
    "    if st.sidebar.button(\"Predict Market Viability & Votes\", type=\"primary\"):\n",
    "        # Construct inference DataFrame\n",
    "        input_data = pd.DataFrame([{\n",
    "            'online_order': online_order,\n",
    "            'book_table': book_table,\n",
    "            'location': location,\n",
    "            'rest_type': rest_type,\n",
    "            'listed_in_type': listed_in_type,\n",
    "            'clean_cost': float(clean_cost),\n",
    "            'clean_rate': float(clean_rate),\n",
    "            'cuisine_count': int(cuisine_count),\n",
    "            'has_dish_liked': int(has_dish_liked),\n",
    "            'cost_per_cuisine': float(cost_per_cuisine)\n",
    "        }])\n",
    "\n",
    "        try:\n",
    "            # Predict log-transformed votes and inverse transform via expm1\n",
    "            log_pred = pipeline.predict(input_data)[0]\n",
    "            predicted_votes = max(0, int(np.expm1(log_pred)))\n",
    "\n",
    "            st.divider()\n",
    "            st.subheader(\"📊 Executive Prediction Output\")\n",
    "            \n",
    "            res_col1, res_col2, res_col3 = st.columns(3)\n",
    "            res_col1.metric(\"Predicted User Votes\", f\"{predicted_votes} Votes\", help=\"Estimated customer engagement volume\")\n",
    "            res_col2.metric(\"Pricing Tier (Cost/2)\", f\"₹{clean_cost}\")\n",
    "            res_col3.metric(\"Service Quality Index\", f\"{clean_rate} / 5.0\")\n",
    "\n",
    "            if predicted_votes > 500:\n",
    "                st.success(\"🌟 **High-Impact Market Segment:** This restaurant profile indicates exceptional market traction and high viral visibility in Bangalore.\")\n",
    "            elif predicted_votes > 150:\n",
    "                st.info(\"👍 **Moderate Viability:** Standard performance tier. Optimizing menu diversification or table booking could elevate engagement.\")\n",
    "            else:\n",
    "                st.warning(\"⚠️ **Niche / Low Engagement Profile:** High risk of low customer visibility unless paired with aggressive delivery promotions.\")\n",
    "\n",
    "        except Exception as ex:\n",
    "            st.error(f\"[INFERENCE ERROR]: {ex}\")\n",
    "\n",
    "# Footer\n",
    "st.divider()\n",
    "st.markdown(\"<p style='text-align: center; color: gray;'>Zomato Bangalore Data Science Master Portfolio | Built with Streamlit & Scikit-Learn</p>\", unsafe_allow_html=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7aff9288-7cfc-43dd-9105-a2df7cb7fe46",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1ac682b9-6c70-4d5d-bba0-11fe8d416fc8",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "49e73e63-47a8-46c9-8775-6e50eee97311",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "04021fec-f08c-46b0-b5d0-07ed1db17beb",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3c6859b7-1378-40f9-949f-ccc45275e06f",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
